version: '2'

services:
  dibimbing-dataeng-jupyter:
    container_name: ${JUPYTER_CONTAINER_NAME}
    hostname: ${JUPYTER_CONTAINER_NAME}
    image: dataeng-dibimbing/jupyter
    ports:
      - ${JUPYTER_PORT}:8888
      - 4043:4040
      - 4044:4041
    environment:
      - JUPYTER_ALLOW_INSECURE_WRITES=true
    volumes:
      - ../:/resources
      - ../notebooks:/home/jovyan/

networks:
  default:
    name: dataeng-network
    external: true
